import { FETCH_POSTS, FETCH_POST } from "../actions/index";
import _ from 'lodash';

export default (state = {}, action) => {
  switch (action.type) {
    case FETCH_POST:
      // const post = action.payload.data;
      // new object with the id as key. [] is doing key interpolation
      return { ...state, [action.payload.data.id]: action.payload.data };
    case FETCH_POSTS:
      return _.mapKeys(action.payload.data, 'id'); // Returns an object from an array having the id as key
    default:                                       // action.payload.data is generated by redux promise
      return state;
  }
}