import { FETCH_POSTS } from "../actions/index";
import _ from 'lodash';

export default (state = {}, action) => {
  switch (action.type) {
    case FETCH_POSTS:
      return _.mapKeys(action.payload.data, 'id'); // Returns an object from an array having the id as key
    default:                                       // action.payload.data is generated by redux promise
      return state;
  }
}